version: "3.7"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER=: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi